export default [
 {
    src: require('../assets/Sizilien/Tempel_segesta.JPG'),
    thumbnail: require('../assets/Sizilien/Tempel_segesta_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: "Tempel in Segesta",
    "lat": 37.941287,
    "lng": 12.831998,
    "description": "Tempel in Segesta",
    "Beschreibung": "Der Tempel in dorischem Baustil steht in einer überblickenden Position auf einem Hügel. Dadurch dass der Tempel nie komplett fertiggestellt wurde tragen die Säulen noch eine Schutzschicht, welche durch Abtragung die Kanneluren formen sollte. Ebenso lassen sich Hinweise auf verwendete Bautechnik finden. So haben beispielsweise die verwendeten Steinblöcke noch die Hebebossen, die zum Einhängen der Seile verwendet wurden. Der Tempel ist auch ein schönes Beispiel für die Verwendung der Kurvatur in der Architektur. Hierbei werden gerade Gebäudekanten absichtlich leicht gewölbt, wodurch das Objekt harmischer aussieht. Auch die Entasis (Schwellung) der Säulen soll diesen Effekt erzielen.",
    "Erreichbarkeit": "Parco Archeologico di Segesta. Contrada Barbaro, 91013 Calatafimi TP. Öffnungszeiten: 9:00 - 16:30",
    "Literatur": "Brigit Carnabuci: Sizilien. Griechische Tempel, römische Villen, normannische Dome und barocke Städte im Zentrum des Mittelmeeres (= DuMont Kunst-Reiseführer). 6., aktualisierte Auflage. DuMont Reiseverlag, Ostfildern 2011, ISBN 978-3-7701-4385-6.         Eva Gründel, Heinz Tomek: Sizilien. DuMont Buchverlag, Köln, 5. Auflage 2001, ISBN 3-7701-3476-1      Dieter Mertens: „Der Tempel von Segesta“ und die Dorische Tempelbaukunst des Griechischen Westens in klassischer Zeit. Verlag Philipp von Zabern, Darmstadt 1984, ISBN 3-8053-0515-X.",
  }, {
    src: require('../assets/Sizilien/Kreuzgang.JPG'),
    thumbnail: require('../assets/Sizilien/Kreuzgang_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: "Kreuzgang des Klosters Monreale",
    "lat": 38.081662,
    "lng": 13.292429,
    "description": "Kreuzgang mit Blick auf Wehrturm",
    "Beschreibung": "Als typisches Element mittelalterlicher Klöster ist der Kreuzgang des Kloster eines der schönsten, noch erhaltenen Beispiele. Die Kapitelle der insgesamt 228 Säulen im arabischen Stil zeigen narrative Darstellungen. Beim Bau konnten die aufwendig hergestellten Säulen und Kapitelle wahrscheinlich nicht termingerecht fertiggestellt werden, die Bögen wurden aber schon auf einem Gerüst gebaut. Davon zeugen die Wulste im inneren der Bögen, mit Öffnungen zum Einsatz von Zapfen. Die fertigen Säulen konnten dann im nachhinein eingefügt werden. Die einzelnen Säulen stehen jeweils auf Bleiplatten. Die Duktilität des Bleis sorgt für eine Art gedäpfte Lagerung der Säulen, wodurch, trotz Erdbeben, alle Säulen noch heute intakt sind.",
    "Erreichbarkeit": "Cattedrale di Monreale, Monreale. In 30 Minuten leicht von Palermo über die SS186 zu erreichen.",
    "Literatur": "Brigit Carnabuci: Sizilien. Griechische Tempel, römische Villen, normannische Dome und barocke Städte im Zentrum des Mittelmeeres (= DuMont Kunst-Reiseführer). 6., aktualisierte Auflage. DuMont Reiseverlag, Ostfildern 2011, ISBN 978-3-7701-4385-6.",
  }, {
    src: require('../assets/Sizilien/Brunnen.JPG'),
    thumbnail: require('../assets/Sizilien/Brunnen_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: "Brunnen",
    "lat": 38.081368,
    "lng": 13.292130,
    "description": "Brunnenhof",
    "Beschreibung": "In der Südwestecke des Kreuzganges befindet sich zusätzlich der aus 3 x 3 Arkaden bestehende Brunnenhof. Als typisches Element der arabischen Architektur zeugt dieser von der Synthese aus arabisch-byzantinisch-normannischer Architektur, die es so nur auf Sizilien gibt.",
    "Erreichbarkeit": "Cattedrale di Monreale, Monreale. In 30 Minuten leicht von Palermo über die SS186 zu erreichen.",
    "Literatur": "Brigit Carnabuci: Sizilien. Griechische Tempel, römische Villen, normannische Dome und barocke Städte im Zentrum des Mittelmeeres (= DuMont Kunst-Reiseführer). 6., aktualisierte Auflage. DuMont Reiseverlag, Ostfildern 2011, ISBN 978-3-7701-4385-6.",
  }, {
    src: require('../assets/Sizilien/Bronzeportal.jpg'),
    thumbnail: require('../assets/Sizilien/Bronzeportal_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: "Bronzeportal",
    lat: 38.081916,
    "lng": 13.291835,
    "description": "Bronzeportal",
    "Beschreibung": "Unter dem im 18. Jahrhundert vorgebauten, klassizistischen Portikus befindet sich das Bronzeportal, vermutlich von Bonannus von Pisa 1186 hergestellt, und zeigt 42 Darstellungen mit biblischen Motiven. Das Spitzbogen-Portal im arabischen-normannischen Stil hat keinen Waagrechten Sturz, der typischen romanischen Kirchen",
    "Erreichbarkeit": "Cattedrale di Monreale, Monreale. In 30 Minuten leicht von Palermo über die SS186 zu erreichen.",
    "Literatur": "Brigit Carnabuci: Sizilien. Griechische Tempel, römische Villen, normannische Dome und barocke Städte im Zentrum des Mittelmeeres (= DuMont Kunst-Reiseführer). 6., aktualisierte Auflage. DuMont Reiseverlag, Ostfildern 2011, ISBN 978-3-7701-4385-6.",
  }, {
    src: require('../assets/Latium/albanersee.JPG'),
    thumbnail: require('../assets/Latium/albanersee_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption:"Entwässerungskanal des Albaner Sees",
    "lat": 41.71224887,
    "lng": 12.69442116,
    "description": "Entwässerungskanal des Albaner Sees",
    "Beschreibung": "Es handelt sich um einen 1.800 Meter langen, künstlichen Kanal, welcher an der Westseite des Albaner Sees liegt. Laut Titus Livius wurde der Kanal zwischen 398 - 397 v. Chr. angelegt. Der Kanal aus geschichtetem Naturstein erbaut, beginnt in einem großen Raum, in welchem sich Wasserablaufschotten befinden. Von dort aus verschwindet der Kanal im Berg und entwässert sich über Feldern.",
    "Erreichbarkeit": "Via dei Pescatori, Castel Gandolfo",
    "Literatur": "Alfred Heuß/Jochen Bleicken: Römische Geschichte, Paderborn u.a., 92003. John Grey Landels: Die Technik in der antiken Welt, München, 41989.",
  },{
    src: require('../assets/Sizilien/Kapitell.JPG'),
    thumbnail: require('../assets/Sizilien/Kapitell_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: "Widmungskapitell: Wilhelm II. widmet Kloster und Kirche der heiligen Maria",
    "lat": 38.081450,
    "lng": 13.292067,
    "description": "Widmungskapitell",
    "Beschreibung": "Die Kathedrale Santa Maria Nuova in Monreale ist, wie der Name vermuten lässt, der heiligen Maria gewidmet. Das Widmungskapitell an einer der viele Säulen des Kreuzganges zeigt Wilhelm den II. wie er Kloster und Kirche der heiligen Maria widmet; ein Engel hilft, den Dom zu tragen. Beachtlich ist die Handwerkskunst mit der die Kapitelle gefertigt wurden. Zusätzlich zum altbekannten Arkanthusblatt werden hier die Kapittelle als architektonisches Element neu entdeckt und erzählen Geschichten aus der Bibel, dem Alltag oder der Mythologie. Alle 104 Doppelkapitelle und die 5 Viererkapitelle des Kreuzganges findet man in digitalisierter Form auf http://cenobium.isti.cnr.it/monreale/capitals    ",
    "Erreichbarkeit": "Cattedrale di Monreale, Monreale. In 30 Minuten leicht von Palermo über die SS186 zu erreichen.",
    "Literatur": "BrigitCarnabuci: Sizilien. Griechische Tempel, römische Villen, normannische Dome und barocke Städte im Zentrum des Mittelmeeres (= DuMont Kunst-Reiseführer). 6., aktualisierte Auflage. DuMont Reiseverlag, Ostfildern 2011, ISBN 978-3-7701-4385-6.",
  }, {
    src: require('../assets/Latium/aquaPark.JPG'),
    thumbnail: require('../assets/Latium/aquaPark_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Park der Aquädukte',
    "lat": 41.85091321,
    "lng": 12.55399734,
    "description": "Park der Aquädukte",
    "Beschreibung": "Der Park der Aquädukte besteht aus Überresten von sieben römischen Aquädukten. Diese Trassen waren für die Frisch- und Nutzwasserversorgung Roms zuständig. Die typisch römische Architektur und Baukunst des echten Bogens lässt sich an den erhaltenen Arkaden erkennen. In den Freispiegelleitungen kann man Überreste des verwendeten Opus Signinum. Dieser Art des Estrichs wurde verwendet um eine wasserdichte, glatte Oberfläche zu schaffen.   ",
    "Erreichbarkeit": "Weblink: http://www.parcoacquedotti.it  --- Parco degli Acquedotti / Parco dei 7 Acquedotti, u.a. folgende Teilabschnitte der Aquädukte: Arkaden der Aquädukte Aqua Claudia, Anio Novus und Acqua Felice; / Teil des Regionalparks Via Appia Antica",
    "Literatur": "Sueton, Caligula 21;  Frontinus, de aquis urbis Romae ;  Helmuth Schneider, Die Wasserversorgung des Imperium Romanum",
  }, {
    src: require('../assets/Latium/villa.JPG'),
    thumbnail: require('../assets/Latium/villa_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Villa des Maxentius',
    "lat": 41.85493348,
    "lng":  12.51962149,
    "description": "Villa des Maxentius",
    "Beschreibung": "Die Villa des Maxentius war ein palastartiger Komplex an der Via Appia gelegen. Herzstück der Villa sind ein gewaltiger Palastwohnbau und ein, dem Circus Maximus nachempfundenen Circus. Eine bautechnische Besonderheit ist die Einlassung von leeren Amphoren in die aus Opus Caementicium bestehenden Gewölbe.",
    "Erreichbarkeit": "Via Appia Antica 153, Rom",
    "Literatur": "Peter Funkte/Hans-Joachim Gehrke: Geschichte der Antike, Stuttgart u.a., 22006.  Alfred Heuß/Jochen Bleicken: Römische Geschichte, Paderborn u.a., 92003.",
  }, {
    src: require('../assets/Latium/viaappia.JPG'),
    thumbnail: require('../assets/Latium/viaappia_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Via Appia Antica',
    "lat": 41.850112,
    "lng": 12.522864,
    "description": "Via Appia Antica",
    "Beschreibung": "Die Via Appia Antica war einst eine der Hauptverkehrsrouten des Römischen Reichs. Heute wird die Straße zum Teil auch noch von Fahrzeugen benutzt. Kurz nach ihrem Beginn am Stadttor San Sebastiano finden sich noch Originalsteine der ursprünglichen Bebauung. Am Straßenrand finden sich eine Vielzahl von römischen Grabmälern.",
    "Erreichbarkeit": "Via Appia Antica, Rom",
    "Literatur": "Dieter Hägermann/Helmuth Schneider: Landbau und Handwerk : 750 v. Chr. bis 1000 n. Chr.. Propyläen-Technikgeschichte Bd 1, Berlin, 2003. Alfred Heuß/Jochen Bleicken: Römische Geschichte, Paderborn u.a., 92003. Vitruv: Über die Baukunst. De architectura, Erich Stürzenacker (Hg.), Essen, 1938.",
  }, {
    src: require('../assets/Sizilien/peristyl.JPG'),
    thumbnail: require('../assets/Sizilien/peristyl_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Peristylhof',
    "lat": 37.430428,
    "lng": 14.481137,
    "description": "Peristylhof",
    "Beschreibung": "Das typisch griechische Peristyl (peri „um herum“ und stylos „Säule“) ist der hier zu sehende, von Säulen umgebene, Innenhof. Dieses architektonische Element wurde auch bei den Römern beliebt. So empfahl Vitruv  für die Villa die Abfolge von Eingang, Peristyl und Atrium in der Mittelachse des Gebäudes, während für das Stadthaus die umgekehrte Abfolge üblich war, bei der im Eingangsbereich das Atrium liegt und das Peristyl im hinteren, privateren Bereich des Hauses.",
    "Erreichbarkeit": "Sito archeologico di Morgantina, erreichbar über die SS288, nahe Piazza Armerina",
    "Literatur": "Wilfried Koch: Baustilkunde, Bertelsmann Lexikon Institut, 2003, ISBN 3-577-10457-0",
  }, {
    src: require('../assets/Sizilien/wasserleitung_detail.JPG'),
    thumbnail: require('../assets/Sizilien/wasserleitung_detail_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Wasserleitung',
    "lat": 38.094158,
    "lng": 13.532066,
    "description": "Wasserleitung - Opus Signinum",
    "Beschreibung": "Ausschnitt einer überdachten Wasserleitung. Es lassen sich die verschieden Schichten des Aufbaus erkennen. Bei der rosa-farbigen Schicht handelt sich um Opus Signinum. Dieser wird aus einem Gemisch aus fein zerschlagenen Tonscherben, Sandsorten, Kalkmörtel, Ziegelmehl sowie Kies, Terracotta- oder Keramikfragmenten und -soweit regional verfügbar- natürlichen Puzzolanen gefertigt. Der erhärtete Estrich wurden mit einer Schicht aus Leinöl überzogen und solange poliert, bis die Oberfläche glatt wie Marmor wurde. Im Falle einer Wasserleitung ging es hierbei nicht um den optischen Eindruck sondern vielmehr darum eine möglichst glatte und wasserdichte Oberfläche zu schaffen, welche Kalkablagerungen verhindert.",
    "Erreichbarkeit": "Area Archeologica di Solunto. Solunto is kurz vor Palermo leicht von der SS113 zu erreichen.",
    "Literatur": " Plinius der Ältere: Naturalis historia. Buch 35, Kapitel 46.  Vitruv: De Architectura. Buch VII, F. Sear: Roman Wall and Vault Mosaics. Heidelberg 1977.",
  }, {
    src: require('../assets/Latium/roemischesvorratslager.jpg'),
    thumbnail: require('../assets/Latium/roemischesvorratslager_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Römische Vorratslager',
    "lat": 41.75506983,
    "lng": 12.28805077,
    "description": "Römische Vorratslager",
    "Beschreibung": "Das römische Vorratslager bestand aus in den Boden eingelassenen Amphoren (dolien), die zumeist mit Öl und Wein gefüllt wurden. Markant ist die Größe der einzelnen Amphoren, welches auf eine dauerhafte Nutzung als stationäre Vorratsgefäße schließen lässt. Die Einlassung der Behälter in den Boden verfolgte den Zweck der Kühlung. Abschließend wurden die Amphoren mit zumeist Lederabdeckungen verschlossen um die Güter vor Witterungseinflüssen und Ungeziefer zu schützen.",
    "Erreichbarkeit": "Archäoligischer Park Ostia Antica; Öffnungszeit je nach Jahreszeit: 9:00 bis 15:30 im Winter und 18:15 im Sommer; Link: ostiaantica.beniculturali.it",
    "Literatur": "Alfred Heuß/Jochen Bleicken: Römische Geschichte, Paderborn u.a., 92003.,Dieter Hägermann/Helmuth Schneider: Landbau und Handwerk : 750 v. Chr. bis 1000 n. Chr.. Propyläen-Technikgeschichte Bd 1, Berlin, 2003. Helmuth Schneider: Geschichte der antiken Technik, München, 22012.",
  }, {
    src: require('../assets/Sizilien/latrine.JPG'),
    thumbnail: require('../assets/Sizilien/latrine_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Latrine',
    "lat": 37.364638,
    "lng": 14.335021,
    "description": "Latrine mit Bodenmosaik",
    "Beschreibung": "Der hier gezeigte Ausschnitt zeigt die Sitzmöglichkeiten einer römischen Latrinen. Man saß nebeneinander und teilweise sich gegenüber während man sich erleichterte. Gut zu sehen ist der Abwasserkanal, der unter den Toilettensitzen verläuft. Durch eine konstante Wasserversorgung wurde Fäkalien weggespült. Nicht selten wurden diese Abwässer in nahe gelegene Felder geleitet und als Dünger verwertet.",
    "Erreichbarkeit": "Villa Romana del Casale, in circa 3 km Entfernung von Piazza Armerina",
    "Literatur": "",
  }, {
    src: require('../assets/Sizilien/hypokaustenheizung2.JPG'),
    thumbnail: require('../assets/Sizilien/hypokaustenheizung2_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Hypokaustum - Unterbau',
    "lat": 37.364871,
    "lng": 14.334114,
    "description": "Hypokaustenheizung, Unterbau",
    "Beschreibung": "Der zu heizende Raum bestand aus im Abstand von etwa 30 bis 40 cm aufgeschichteten, etwa 30 bis 60 cm hohen Ziegeltürmchen aus quadratischen Platten. Auf diesen Türmchen wurden größere Deckplatten aufgebracht auf welchen wiederum eine große Tragplatte mit Estrich lag. Diese relative dicke Konstruktion benötigte mehrere Stunden, wenn nicht ein oder zwei Tage bis zur völligen Erwärmung. Die heiße Luft strömte an den Wandkanälen (tubuli) in Freie. Auf diese Weise konnten auch die Wände des Raums beheizt werden.",
    "Erreichbarkeit": "Villa Romana del Casale, in circa 3 km Entfernung von Piazza Armerina",
    "Literatur": "Gustav Fusch: Über Hypokausten-Heizungen und mittelalterliche Heizungsanlagen. Dissertation Hannover 1910. Heinz-Otto Lamprecht: Heizung. In: Der Neue Pauly (DNP). Band 5, Metzler, Stuttgart 1998, ISBN 3-476-01475-4, Sp. 258–261. Hannes Lehar: Die römische Hypokaustheizung. Berechnungen und Überlegungen zu Leistung, Aufbau und Funktion. Shaker, Aachen 2012",
  }, {
    src: require('../assets/Sizilien/ziegelmauer.JPG'),
    thumbnail: require('../assets/Sizilien/ziegelmauer_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Lehmziegelmauer',
    "lat": 37.071284,
    "lng": 14.223443,
    "description": "Lehmziegelmauer",
    "Beschreibung": "Im Jahre 333 vor Christus wurde diese 8 Meter hohe Befestigungsmauer errichtet. Sie diente dazu, große Sandmengen, die von der Küste in Richtung der Stadt geweht wurden aufzuhalten. Die Befestigungsanlage ist noch sehr gut erhalten, da sie bis zu ihrer Entdeckung im 20ten Jahrhundert von Dünen bedeckt war.",
    "Erreichbarkeit": "Fortificazioni Greche di Capo Soprano (Mura Timoleontee), Gela",
    "Literatur": "https://www.lonelyplanet.com/italy/gela/attractions/greek-fortifications-of-capo-soprano/a/poi-sig/1024037/1003652                                            ----- http://www.sicilia-by-divino.com/gela.html",
  }, {
    src: require('../assets/Sizilien/Muehle.jpg'),
    thumbnail: require('../assets/Sizilien/Muehle_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Mühle',
    "lat": 37.4310005,
    "lng": 14.4785498,
    "description": "Mühle",
    "Beschreibung": "Das Getreide wurde in die trichterförmige Öffnung der Steinmühle gegeben und zwischen den Mahlsteinen zerrieben. Der obere Mahlstein konnte mittels einer Vorrichtung aus Holz durch menschliche oder tierische Arbeit in Bewegung gesetzt werden. Steinmühlen konnten große Mengen an Getreide in relativ kurzer Zeit mahlen.",
    "Erreichbarkeit": "Sito archeologico di Morgantina, erreichbar über die SS288, nahe Piazza Armerina",
    "Literatur": "http://www.amuseum.de/physik/alwaze/alwazehist.htm",
  }, {
    src: require('../assets/Sizilien/hypokaustenheizung1.JPG'),
    thumbnail: require('../assets/Sizilien/hypokaustenheizung1_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Hypokaustum - Ofen',
    "lat": 37.364977,
    "lng": 14.333966,
    "description": "Hypokaustenheizung, Ofen",
    "Beschreibung": "Der hier sichtbare Teil des Heizungssystems der Thermen der Villa Romana del Casale, einer spätrömischen Villa urbana, zeigt einen Brennofen. Hier wurde Holz verbrannt um mit der heißen Luft den, unter dem Fußboden liegenden, Heizraum zu erwärmen. Als typisches Merkmal der römischen Baukunst ist die Rundbogenkonstruktion zu erkennen. Tatsächlich war der gesammte Brennraum mit einem Tonnengewölbe überdacht. Hinweise auf dieses Gewölbe lassen sich an den Innenwänden erkennen. Hier befinden sich Reste der holen Tonzylinder, die durch das Zusammenstecken einen Bogen spannten.",
    "Erreichbarkeit": "Villa Romana del Casale, in circa 3 km Entfernung von Piazza Armerina",
    "Literatur": "Gustav Fusch: Über Hypokausten-Heizungen und mittelalterliche Heizungsanlagen. Dissertation Hannover 1910. Heinz-Otto Lamprecht: Heizung. In: Der Neue Pauly (DNP). Band 5, Metzler, Stuttgart 1998, ISBN 3-476-01475-4, Sp. 258–261. Hannes Lehar: Die römische Hypokaustheizung. Berechnungen und Überlegungen zu Leistung, Aufbau und Funktion. Shaker, Aachen 2012,",
  }, {
    src: require('../assets/Sizilien/ziegelofen.JPG'),
    thumbnail: require('../assets/Sizilien/ziegelofen_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Brennofen',
    "lat": 37.430647,
    "lng": 14.480064,
    "description": "Brennofen",
    "Beschreibung": "Dieser Ausschnitt ziegt die obere Öffnung eines Brennofens. Darunter wurden keramische Objekte gestapelt und gebrannt. Die Löcher dienten dienten als Abluftkanäle. Die Kapazität dieser Öfen verierte, in einigen Baurten konnten aber mehrere tausend Teile gebrannt werden. Gefeuert wurde in einer separaten Brennkammer von der aus die heiße Luft in den Ofen und anschließend in Freie strömte.",
    "Erreichbarkeit": "Sito archeologico di Morgantina, erreichbar über die SS288, nahe Piazza Armerina",
    "Literatur": "http://www.antike-tischkultur.de/keramikbrennofen.html",
  }, {
    src: require('../assets/Sizilien/theater.JPG'),
    thumbnail: require('../assets/Sizilien/theater_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Griechisches Theater',
    "lat": 37.430078,
    "lng": 14.479334,
    "description": "Griechisches Theater",
    "Beschreibung": "Das in einen flachen Hang integrierte Freilufttheater bestand aus kreisförmig angeordneten Stufen, welche die nicht mehr erhaltene Orchestra umgaben. Diese Sitzreihen wurden durch die im Bild erkennbaren horizontale Korridore (Diazoma) unterteilt. Resultat der typischen Bauweise der griechischen Theater war und ist die hervorragende Akustik.",
    "Erreichbarkeit": "Sito archeologico di Morgantina, erreichbar über die SS288, nahe Piazza Armerina",
    "Literatur": "http://griechischestheater.npage.de/bauweise.html",
  }, {
    src: require('../assets/Sizilien/griechischesbad.JPG'),
    thumbnail: require('../assets/Sizilien/griechischesbad_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Griechisches Bad',
    "lat": 37.072637,
    "lng": 14.230494,
    "description": "Griechisches Bad",
    "Beschreibung": "Die griechischen Bäder von Gela datieren auf das vierte oder dritte Jahrhundert vor Christus. Sie setzten sich aus zwei verschiedenen Räumen zusammen, die wahrscheinlich von einem typischen Terrakotta Dach bedeckt waren. Im ersten Raum befanden sich mehrere Becken, kreisförmig angeordnet und durch Rohre miteinander verbunden. Es gab keinen Abfluss. Die Becken mussten von Hand geleert werden. Im zweiten Raum diente der untere Teil als Hypokaustum - vermutlich für eine darüberliegende Sauna. ",
    "Erreichbarkeit": "Innenstadt Gela, Via Europa",
    "Literatur": "Pietro Orlandini: Gela. Impianto greco di bagni pubblici presso l'ospizio, in Notizie degli scavi, 1960. Der Neue Pauly (DNP). Band 5, Metzler, Stuttgart 1998, ISBN 3-476-01475-4, Sp. 258–261.",
  }, {
    src: require('../assets/Latium/hadriankanal.png'),
    thumbnail: require('../assets/Latium/hadriankanal_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Kanal der Hadrians Villa',
    "lat": 41.939015,
    "lng": 12.775790,
    "description": "Kanal der Hadrians Villa",
    "Beschreibung": "Langes, rechteckiges Wasserbecken, welches an den Kanal von Canopus angelehnt ist, welcher die ägyptische Stadt Alexandria mit dem Nil verband. Im Süden des Canopus befand sich ein Nymphäum (Serapeum), welches für Bankette und (nächtliche) Sommerfeste genutzt wurde. Das Wasserbecken (119 x 18 Meter) wurde von der östlichen Seite von einer doppelten und auf der Westseite von einer einfachen Säulenreihe gesäumt. Diese wird in der Mitte durch sechs Statuen unterbrochen. Die Kolonnenreihe an der Kurve wird durch griechische Götter geziert. Die im Wasser befindlichen Statuen stellen die Verbildlichungen des Nil und des Tiber, sowie ein Krokodil dar.",
    "Erreichbarkeit": "Tivoli, Hadrian Villa; Öffnungszeiten Nov/Dez/Jan: 9:00 - 17:00, Feb: 9:00 - 18:00, Mar/Oct: 9:00 - 18:30, Apr/Sep: 9:00 - 19:00, Mai bis Aug: 9:00 - 19:30; Link: villaadriana.beneculturali.it",
    "Literatur": "Die statuarische Ausstattung der Villa Hadriana bei Tivoli (= Europäische Hochschulschriften. Reihe 38: Archäologie. 4). Lang, Frankfurt am Main u. a. 1983, ISBN 3-8204-7578-8 (Zugleich: Berlin, Freie Universität, Dissertation, 1980).",
  }, {
    src: require('../assets/Latium/ponte.png'),
    thumbnail: require('../assets/Latium/ponte_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Ponte Lucano',
    "lat": 41.954880,
    "lng": 12.761812,
    "description": "Ponte Lucano",
    "Beschreibung": "Gut erhaltene Sieben-Bogen Brücke nahe der Hadrian Villa. Die Brücke gehört zum Archäologischen Park von Tivoli und führt über den Fluss Anio. Bis zur Mitte des 20. Jh. wurde die Brücke genutzt und nun durch eine neue Brücke ersetzt; ist aber für Fußgänger nachwievor nutzbar.",
    "Erreichbarkeit": "Tivoli, freier Zugang",
    "Literatur": "Heinz-Otto Lamprecht: Opus Caementitium. Bautechnik der Römer, Vbt Verlag Bau U. Technik, 1996",
  }, {
    src: require('../assets/Latium/viadipapa.png'),
    thumbnail: require('../assets/Latium/viadipapa_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Via di Papa',
    "lat": 41.75153952,
    "lng": 12.70486592,
    "description": "Via di Papa",
    "Beschreibung": "Sehr gut erhaltene römische Straße in Rocca die Papa bei Rom. Die Straße aus typisch römischen Pflasterstein wird heute noch benutzt.",
    "Erreichbarkeit": "Rocca die Papa, freier Zugang (öffentliche Straße über den Berg)",
    "Literatur": "Heinz-Otto Lamprecht: Opus Caementitium. Bautechnik der Römer, Vbt Verlag Bau U. Technik, 1996",
  }, {
    src: require('../assets/Latium/LatrineNeptune.JPG'),
    thumbnail: require('../assets/Latium/LatrineNeptune_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Latrine der Neptun Therme',
    "lat": 41.75720243,
    "lng": 12.29240181,
    "description": "Latrine der Neptun Therme",
    "Beschreibung": "Die Neptun therme verfügt über seine eigene öffentliche Latrine im Süden der Anlage. Die Sitzbank, auf denen sich die Römer niederließen waren zumeist aus Holz oder Stein gefertigt. Die steinerne Sitzbank dieser Latrine sind ist sehr gut erhalten. Unter der Sitzbank befindet sich eine größere Rinne, die von Wasser dauerhaft durchspült wurde und die Fäkalien in spezielle Behälter oder nahe gelegene Flüsse leitete. Die Latrine galt als Ort für Gespräche und Geschäfte, war nach Geschlechtern getrennt und in Städten an zentralen Punkten errichtet.",
    "Erreichbarkeit": "Archäologischer Park Ostia Antica, Öffnungszeit je nach Jahreszeit: 9:00 bis 15:30 im Winter und 18:15 im Sommer    Link: ostiaantica.beniculturali.it",
    "Literatur": "Richard Neudecker: Die Pracht der Latrine – Zum Wandel öffentlicher Bedürfnisanstalten in der kaiserzeitlichen Stadt. München, 1994",
  }, {
    src: require('../assets/Latium/tubuli.JPG'),
    thumbnail: require('../assets/Latium/tubuli_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Unterbau der Neptun Therme',
    "lat": 41.75672445,
    "lng": 12.29241524,
    "description": "Unterbau der Neptun Therme",
    "Beschreibung": `Die Neptun Therme in Ostia ist besonders für ihre schwarz-weiß Mosaike bekannt. Neben gut erhaltenen Mosaiken hat auch der Aufbau der Terme bis heute überlebt. Besonders die  Unterkonstruktion, das Hypocaustum, ist bei der Neptun Terme noch gut zu erkennen. Auch die Öfen zur Beheizung sind teilweise noch vorhanden. Das Hypocaustum ist eine Warmluftheizung, die in römischen Bädern das caldarium beheizte. Die benötigten Öfen (praefurnium) befanden sich im Freien und leiteten die warme Luft ins Hypocaustum. Im Inneren des Hypocaustum befinden sich kleine Ziegeltürmchen von 30cm bis 60cm Höhe, die eine Tragplatte trugen. Die Ziegeltürmchen bestehen aus viereckigen oder runden einzelnen Ziegelplatten, die mit Hilfe von Mörtel übereinander geschichtet wurden. Auf die abschließende Tragplatte wurde zuerst Mörtel und dann die Mosaike aufgetragen. Diese relative dicke Konstruktion benötigte mehrere Stunden, wenn nicht ein oder zwei Tage bis zur völligen Erwärmung. Über den Hohlraum im Hypocaustum erwärmt sich nicht nur der Boden. Auch in die Wände wurde die warme Luft mittels hohler Röhrenziegel (tubuli) geleitet. Ebenso konnten beheizte Sitzbänke mit dieser Technik verwirklicht werden.`,
    "Erreichbarkeit": "Öffnungszeit je nach Jahreszeit: 9:00 bis 15:30 im Winter und 18:15 im Sommer    Link: ostiaantica.beniculturali.it",
    "Literatur": "Inge Nielsen: Thermae et balnae. The architecture and cultural history of roman public baths, Arhus, 1990",
  }, {
    src: require('../assets/Latium/Baeckerei.JPG'),
    thumbnail: require('../assets/Latium/Baeckerei_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Mühlen der Bäckerei',
    "lat": 41.75497325,
    "lng": 12.28943535,
    "description": "Mühlen der Bäckerei",
    "Beschreibung": "Um 170 v. Chr. entstand das Bäckereigewerbe im antiken Rom. Die Bäckerei in Ostia Antica ist gut erhalten und verfügt über einige noch gut erhaltene Mühlen im Hinterhof. Die Mühlen aus Stein bestehen aus einem kegelförmigen Unterbau mit einem zylinderförmigen Aufsatz zwischen denen Getreide gemahlen wurde. Zum drehen des Zylinders wurde ein Holzbalken verwendet, der durch Maulesel oder Menschen betrieben wurde. Auch der Back- und Verkaufsraum ist gut erhalten. Ein Steintresen trennt den Raum für Kunden vom Geschäftsbereich ab. Die Waren konnten zudem direkt raus auf die Straße durch eine Wandöffnung verkauft werden, Brot wurde gewürzt in Keramikformen im Lehmofen gebacken.",
    "Erreichbarkeit": "Öffnungszeit je nach Jahreszeit: 9:00 bis 15:30 im Winter und 18:15 im Sommer    Link: ostiaantica.beniculturali.it",
    "Literatur": "",
  }, {
    src: require('../assets/Latium/tempelforum.png'),
    thumbnail: require('../assets/Latium/tempelforum_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Tempel am Forum',
    "lat": 41.7544274,
    "lng": 12.28801461,
    "description": "Tempel am Forum",
    "Beschreibung": "Errichtet im 1. Jh. n. Chr., Römer, Sakralbau. Am südlichen Ende des Forums befinden sich die Überreste dieses Tempels, der unter Tiberius errichtet wurde. Die Reste der Grundmauern lassen eine Vielzahl kleinerer Räume erkennen, die sich auf einer Bodenplatte befunden haben. Der Tempel war ungefähr 16 Meter hoch und wurde teilweise aus Marmor errichtet; dieser Tempel scheint das früheste Bauwerk in Ostia zu sein, in dem Marmor in größeren Mengen verbaut wurde. Vor dem Tempel befanden sich zur Zierde sechs Säulen, neben dem Bau Bögen aus Ziegeln, die unter Hadrian hinzu kamen. Teile der Rückwand des Tempels sind heute rekonstruiert und neben den Tempelresten zu besichtigen.",
    "Erreichbarkeit": "",
    "Literatur": "Douglas Boin: Ostia in Late Antiquity. Cambridge 2013; Anna-Katharina Rieger: Heiligtümer in Ostia. Pfeil, München, 2004",
  }, {
    src: require('../assets/Latium/mithras.JPG'),
    thumbnail: require('../assets/Latium/mithras_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Mithrasthermen',
    "lat": 41.75430932,
    "lng": 12.28494678,
    "description": "Mithrasthermen",
    "Beschreibung": "Errichtet 1. bis 2. Jh. n. Chr., Römer, Profanbau. Die Mithrasthermen (Terme del Mitra) wurden in hadrianischer Zeit errichtet und im frühen 4. Jahrhundert verändert. Die Wände der Thermen waren mit Portraitbüsten; Besonders gut erhalten sind die unterirdischen Wasserversorgungsinstallationen: Hier stand einst ein großes Rad, welches mit einem zweiten verbunden war, an dem Eimer hingen, die Wasser aus einer Zisterne in das Bad beförderten. Das Rad wurde wahrscheinlich von einem Sklaven betrieben, wobei in einer Stunde ca. 1000 Liter Wasser transportiert werden konnten. Das ebenfalls gut erhaltene Mitreo delle terme del Mitra („Mithräum der Mithrasthermen“) war eines der Heiligtümer für den aus dem Osten stammenden Mysterienkult des Mithras.",
    "Erreichbarkeit": "",
    "Literatur": "Werner Heinz: Römische Thermen, Badewesen und Badeluxus, München, 1983; Ulrika Kiby: Bäder und Badekultur in Orient und Okzident. Antike bis Spätbarock, Köln, 1995",
  }, {
    src: require('../assets/Latium/weisen.JPG'),
    thumbnail: require('../assets/Latium/weisen_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Therme der Sieben Weisen',
    "lat": 41.75308726,
    "lng": 12.28489288,
    "description": "Therme der Sieben Weisen",
    "Beschreibung": "Errichtet im 2. Jh. n. Chr., Römer Profanbau. Die Thermen der Sieben Weisen (Terme dei Sette Sapienti) liegen im Westteil von Ostia und sind ein gut erhaltenes Beispiel für ein mittelgroßes römisches Badehaus; Zentrum der Anlage bildet ein runder Saal, auf dem sich einst eine Kuppel befand. In diesem Saal befand sich auch ein Kaltbad, durch Bögen gelangte man von hier in die anderen Baderäume. Ein zweiter Raum, ein Warmbad (Caldarium) ist mit einem Mosaik mit der Darstellung von Eroten auf Seepferden ausgestattet, in einem dritten Baderaum, dem Kaltbaderaum (Frigidarium), findet sich die Wandmalerei einer badenden Venus. Das Bad war einst reich mit Skulpturen ausgestattet. Der Fußboden zeigt ein schwarz-weißes Mosaik mit Jagddarstellungen; Bemerkenswert sind darüber hinaus die zahlreichen gut erhaltenen Wandmalereien.",
    "Erreichbarkeit": "",
    "Literatur": "Ulrika Kiby: Bäder und Badekultur in Orient und Okzident. Antike bis Spätbarock, Köln, 1995; Marga Weber: Antike Badekultur, o.O., 1996",
  }, {
    src: require('../assets/Latium/diana.JPG'),
    thumbnail: require('../assets/Latium/diana_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Haus der Diane',
    "lat": 41.75475087,
    "lng": 12.28858519,
    "description": "Haus der Diane",
    "Beschreibung": `Errichtet Mitte des 2. Jh. n. Chr., Römer, Profanbau.
      Das Caseggiato di Diana ist ein mehrstöckiges Mietshaus und Teil der Insula III. Insula ist die Bezeichnung des Häuserblocks in meist rechtwinklig angelegten Städten im Altertum, insbesondere im römischen Weltreich. Im engeren Sinne werden damit römische Mietshäuser bezeichnet. Die Insulae wurden meist aus luftgetrockneten Ziegeln erbaut, die sich bei Hochwasser vollsogen und zusammenbrachen. Dies war bei gebrannten Ziegeln nicht möglich, doch diese waren aufwändiger herzustellen und somit teurer. Selbst die Qualität der luftgetrockneten Ziegel muss sehr gering gewesen sein, denn normalerweise dürften auch sie nach einer Überschwemmung nicht zerfallen. Bei den teureren Häusern mit gebrannten Ziegeln wurden diese oft als Mauerschalen genutzt, zwischen die Opus Caementicium, eine Art antiker Beton aus Sand, Kalkwasser und grobem oder feinem Kies, gegossen wurde. Für die Fundamentierung, Boden- und Deckenkonstruktionen, für die Dachkonstruktion, die Treppenhäuser, die Balkone (soweit es welche gab), die Fensterläden und die Türen wurde Holz verwendet. Das Haus der Diana erhielt seinen Namen durch ein Terrakottarelief mit dem Bild der Diana, das sich an der Wand des Hofes befindet. Im Untergeschoss befinden sich vor allem Ladengeschäfte. Im zweiten Stockwerk befand sich ein an der Fassade umlaufender Balkon. In verschiedenen Räumen ließen sich gut erhaltene Wandmalereien finden.`,
    "Erreichbarkeit": "",
    "Literatur": "Angelo Pellegrino: Ostia antica. Führer zu den Ausgrabungen. Ed. Abete, Rom, 2000; Marion Bolder-Boos: Ostia. Der Hafen Roms. von Zabern, Darmstadt, 2014; Dirk Steuernagel: Kult und Alltag in römischen Hafenstädten. Soziale Prozesse in archäologischer Perspektive. Potsdamer altertumswissenschaftliche Beiträge. Bd 11, Steiner; Stuttgart, 2004",
  }, {
    src: require('../assets/Provence/nimes_amphi.png'),
    thumbnail: require('../assets/Provence/nimes_amphi_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Nîmes: Amphitheater',
    "lat": 43.834942,
    "lng": 4.359632,
    "description": "Nîmes: Amphitheater",
    "Beschreibung": `Das Amphitheater in Nîmes ist eines der besterhaltenen Amphitheater. Es wurde um 90 n. Chr. erbaut. Das Amphitheater zeigt die typische römische Bautechnik ihrer Zeit: Wände, Bögen und Gewölbe in mörtellosem Quadermauerwerk, Mauern aus behauenem Naturstein (opus incertum) und sogenanntem „römischen Beton“ (opus caementicium). Die Unterbühne (hypogaeum), mit ihrer gegebenenfalls noch vorhandenen Bühnentechnik, ist leider nicht zugänglich.`,
    "Erreichbarkeit": "Boulevard des Arènes, 30000 Nîmes",
    "Literatur": "Heinz-Otto Lamprecht: Opus caementicium: Bautechnik der Römer, Düsseldorf 1996. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/nimes_maisoncarree.png'),
    thumbnail: require('../assets/Provence/nimes_maisoncarree_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Nîmes: Maison Carrée',
    "lat": 43.838236,
    "lng": 4.356098,
    "description": "Nîmes: Maison Carrée",
    "Beschreibung": `Das Maison Carrée ist einer der besterhaltenen römischen Tempel. Der Podiumstempel entstand zwischen 20 und 12 v. Chr. Architektonisch repräsentiert das Gebäude die augusteische Klassik, die sich stark an der griechischen Architektur orientierte. Das Bauwerk besteht hauptsächlich aus „römischem Beton“ (opus caementicium), während das Quadermauerwerk der Fassaden durch Putz und Kalksteinplatten imitiert wurde – moderne römische Bautechnik in griechischem Gewand.`,
    "Erreichbarkeit": "Place de la Maison Carrée, 30000 Nîmes",
    "Literatur": "Hans Koepf: Baukunst in fünf Jahrtausenden, Stuttgart 1990. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/nimes_porteauguste.png'),
    thumbnail: require('../assets/Provence/nimes_porteauguste_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Nîmes: Porte Auguste',
    "lat": 43.839490,
    "lng": 4.363134,
    "description": "Nîmes: Porte Auguste",
    "Beschreibung": `Das Augustustor zählt zu den Stadttoren des römischen Nîmes, von denen nur noch zwei Tore erhalten sind. Es besteht fast ausschließlich aus mörtellos versetztem Quadermauerwerk. Kalksteinbögen überspannen die vier Durchlässe, jeweils zwei für Fußgänger und zwei für Fahrzeuge. Die Aussparungen für das Einlegen von Balken zum Verriegeln der Tore sind an einem der Tordurchlässe noch gut erkennbar. Verkehrsgeschichtlich interessant ist die durch das Tor führende Straße, die Via Domitia. Sie verband die Spanien mit Italien und durchquerte auf ihrem Weg auch Nîmes.`,
    "Erreichbarkeit": "25B Boulevard Amiral Courbet, 30000 Nîmes",
    "Literatur": "Dominique Darde: Nîmes antique. In: „Guides archéologiques de la France”, Centre des Monuments Nationaux, Paris 2005, S. 71.",
  }, {
    src: require('../assets/Provence/glanum_wohnhaus.png'),
    thumbnail: require('../assets/Provence/glanum_wohnhaus_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Glanum: Wohnhäuser',
    "lat": 43.773606,
    "lng": 4.833062,
    "description": "Glanum: Wohnhäuser",
    "Beschreibung": `Im nördlichen Teil des Ausgrabungsgeländes von Glanum befinden sich gute Beispiele römisch-griechischer Wohnhäuser, deren Überreste den Stil des antiken Atrium- bzw. Peristylhauses noch gut erkennen lassen. Ursprünglich stammen diese Gebäude aus hellenistischer Zeit. Die entsprechende Bauweise aus Natursteinquadern ist noch gut erkennbar. In einigen Wohnhäusern sind noch Wasserbecken (Impluvium) vorhanden. Mindestens eines der Häuser verfügt über eine Zisterne. Auch die Abwasserleistungen zum Abwasserkanal unter der Hauptstraße sind noch vorhanden.`,
    "Erreichbarkeit": "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    "Literatur": "Anne Roth-Congès: Glanum, Vom kelto-ligurischen Oppidum zur gallorömischen Stadt, Paris 2001 u. 2012. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/glanum_markt.png'),
    thumbnail: require('../assets/Provence/glanum_markt_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Glanum: Markt',
    "lat": 43.773606,
    "lng": 4.833062,
    "description": "Glanum: Markt",
    "Beschreibung": `Der noch in seinen Grundmauern erhaltene kleine Markt von Glanum diente vermutlich nicht nur dem Handel, sondern auch der handwerklichen Arbeit. Technische Artefakte der handwerklichen Produktion sind aber nicht mehr erkennbar. Obwohl die Gebäude im Altertum mehrmals umgebaut wurden, lässt sich die ursprüngliche hellenistische Bauweise aus Natursteinblöcken stellenweise noch gut erkennen.`,
    "Erreichbarkeit": "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    "Literatur": "Anne Roth-Congès: Glanum, Vom kelto-ligurischen Oppidum zur gallorömischen Stadt, Paris 2001 u. 2012. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/glanum_strasse.png'),
    thumbnail: require('../assets/Provence/glanum_strasse_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Glanum: Straße mit unterirdischer Kanalisation',
    "lat": 43.773606,
    "lng": 4.833062,
    "description": "Glanum: Straße mit unterirdischer Kanalisation",
    "Beschreibung": `Unter der Hauptstraße von Glanum verläuft der Hauptabwasserkanal der Stadt. Er ist noch teilweise durch Steinplatten abgedeckt, aber an manchen Stellen gut einsehbar. Die Abwasserzuflüsse der einzelnen Häuser sind teilweise noch erhalten.`,
    "Erreichbarkeit": "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    "Literatur": "Anne Roth-Congès: Glanum, Vom kelto-ligurischen Oppidum zur gallorömischen Stadt, Paris 2001 u. 2012. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/glanum_therme.png'),
    thumbnail: require('../assets/Provence/glanum_therme_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Glanum: Therme',
    "lat": 43.773606,
    "lng": 4.833062,
    "description": "Glanum: Therme",
    "Beschreibung": `Die Überreste der Therme von Glanum lassen die wichtigsten Bereiche einer römischen Thermenanlage noch gut erkennen (caldarium, frigidarium, tepidarium, apodytherium, natacio etc.). Von besonderem technikhistorischem Interesse sind die Fußbodenheizung (hypogaeum), einschließlich des Heizraumes (praephonium), sowie die Zuflüsse für Frischwasser und der Abfluss für Abwasser. Die Therme wurde in typisch römischer Bauweise aus opus incertum erbaut.`,
    "Erreichbarkeit": "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    "Literatur": "Anne Roth-Congès: Glanum, Vom kelto-ligurischen Oppidum zur gallorömischen Stadt, Paris 2001 u. 2012. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/glanum_brunnen.png'),
    thumbnail: require('../assets/Provence/glanum_brunnen_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Glanum: Dromos-Brunnen',
    "lat": 43.773606,
    "lng": 4.833062,
    "description": "Glanum: Dromos-Brunnen",
    "Beschreibung": `Der gut erhaltene Dromos-Brunnen im Zentrum von Glanum repräsentiert einen typischen Brunnen aus der griechischen Zeit. Der Zugang erfolgt über eine versetzte Steintreppe. Der Brunnen versorgte die Bewohner des umliegenden Stadtviertels. Zentrale Fernwasserversorgungen erhielten die Städte der Provence erst in römischer Zeit.`,
    "Erreichbarkeit": "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    "Literatur": "Anne Roth-Congès: Glanum, Vom kelto-ligurischen Oppidum zur gallorömischen Stadt, Paris 2001 u. 2012. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/glanum_nymphaeum.png'),
    thumbnail: require('../assets/Provence/glanum_nymphaeum_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Glanum: Nymphaeum ',
    "lat": 43.773606,
    "lng": 4.833062,
    "description": "Glanum: Nymphaeum ",
    "Beschreibung": `Das Nymphaeum von Glanum stammt aus gallischer Zeit ist ein tiefer Grundwasserbrunnen mit kultischer Bedeutung. Ursprünglich handelt es sich hier lediglich um ein eingetieftes Wasserbecken. Erst in griechischer Zeit wurde es mit Steinquadern ausgekleidet und mit einer Treppe versehen, die zum Wasser hinabführt.`,
    "Erreichbarkeit": "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    "Literatur": "Anne Roth-Congès: Glanum, Vom kelto-ligurischen Oppidum zur gallorömischen Stadt, Paris 2001 u. 2012. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/glanum_weinraeucherei.png'),
    thumbnail: require('../assets/Provence/glanum_weinraeucherei_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Glanum: Weinräucherei',
    "lat": 43.773606,
    "lng": 4.833062,
    "description": "Glanum: Weinräucherei",
    "Beschreibung": `Die Weinräucherei im nördlichen Teil der Ausgrabungsstätte von Glanum ist ein interessantes Beispiel für römische Lebensmittelproduktion. Um den Wein schneller reifen zu lassen, wurde der Most erwärmt. Dazu stellten die römischen Kellermeister die Weinamphoren in die Sonne oder erwärmten sie, wie hier, mithilfe einer Feuerung.`,
    "Erreichbarkeit": "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    "Literatur": "Anne Roth-Congès: Glanum, Vom kelto-ligurischen Oppidum zur gallorömischen Stadt, Paris 2001 u. 2012. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/glanum_keltisch.png'),
    thumbnail: require('../assets/Provence/glanum_keltisch_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Glanum: Keltische Wohnhäuser',
    "lat": 43.773606,
    "lng": 4.833062,
    "description": "Glanum: Keltische Wohnhäuser",
    "Beschreibung": `Im nordöstlichsten Teil der Ausgrabungsstätte von Glanum sind die Grundmauern der ursprünglichen keltischen Wohnbebauung erhalten. Sie zeigen die in dieser Region typische keltische Bauweise aus Trockensteinmauerwerk. Charakteristisch sind auch die geringen Ausmaße der einzelnen Wohnhäuser, die häufig nur einen Raum besaßen.`,
    "Erreichbarkeit": "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    "Literatur": "Anne Roth-Congès: Glanum, Vom kelto-ligurischen Oppidum zur gallorömischen Stadt, Paris 2001 u. 2012. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/glanum_kenotaph.png'),
    thumbnail: require('../assets/Provence/glanum_kenotaph_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Glanum: Mausoleum/Kenotaph',
    "lat": 43.776387,
    "lng": 4.831043,
    "description": "Glanum: Mausoleum/Kenotaph",
    "Beschreibung": `Die Funktion des Bauwerkes ist nicht vollständig geklärt. Es könnte sich sowohl um ein Mausoleum, als auch um ein Kenotaph handeln. Das Bauwerk entstand vermutlich im frühen 1. Jhd. Von besonderem technikhistorischem Interesse sind die Reliefs mit Schlachtendarstellung, die römische und gallische Waffentechnik zeigen. Dazu gehören unter anderem Lanzen, Schwerter, Schilder, Helme und Kriegshörner.`,
    "Erreichbarkeit": "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    "Literatur": "Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/glanum_bogen.png'),
    thumbnail: require('../assets/Provence/glanum_bogen_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Glanum: Ehrenbogen',
    "lat": 43.776387,
    "lng": 4.831043,
    "description": "Glanum: Ehrenbogen",
    "Beschreibung": `Im nordöstlichsten Teil der Ausgrabungsstätte von Glanum sind die Grundmauern der ursprünglichen keltischen Wohnbebauung erhalten. Sie zeigen die in dieser Region typische keltische Bauweise aus Trockensteinmauerwerk. Charakteristisch sind auch die geringen Ausmaße der einzelnen Wohnhäuser, die häufig nur einen Raum besaßen.`,
    "Erreichbarkeit": "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    "Literatur": "Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/glanum_strasse.png'),
    thumbnail: require('../assets/Provence/glanum_strasse_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Glanum: Via Domitia mit Stützmauer',
    "lat": 43.7775800,
    "lng": 4.8291799,
    "description": "Glanum: Via Domitia mit Stützmauer",
    "Beschreibung": `Die Via Domitia war eine der wichtigsten römischen Fernstraßen. Sie führte von Italien, über die Alpen und durch die Provence, bis nach Spanien. In der Nähe von Glanum folgte die Straße dem steilen Ufer eines Baches. Zur Sicherung gegen das Abrutschen wurde in diesem Abschnitt eine Stützmauer errichtet, von der sich noch ein längerer Teil erhalten hat. `,
    "Erreichbarkeit": "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    "Literatur": "Anne Roth-Congès: Glanum, Vom kelto-ligurischen Oppidum zur gallorömischen Stadt, Paris 2001 u. 2012. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/saint_chamas_pontflavien.png'),
    thumbnail: require('../assets/Provence/saint_chamas_pontflavien_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Saint-Chamas: Pont Flavien',
    "lat": 43.5413508,
    "lng": 5.0430260,
    "description": "Saint-Chamas: Pont Flavien",
    "Beschreibung": `Der Pont Flavien zählt zu den besterhaltenen römischen Straßenbrücken Südfrankreichs. Die Brücke über den Fluss Touloubre besteht aus einem weiten Bogen und besitzt noch beide Portale. Über den Pont Flavien führte die Via Iulia Augusta (später auch Via Aurelia genannt), die Ligurien mit der Provinz Gallia Narbonensis verband. Heute dient sie nur noch dem Fußgängerverehr.`,
    "Erreichbarkeit": "Lotissement Flavien, 13250 Saint-Chamas",
    "Literatur": "Marcel Prade: Les ponts, monuments historiques: inventaire, description, histoire des ponts et ponts-aqueducs de France, protégés au titre des monuments historiques. Poitiers 1986. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/barbegal_muehlen.png'),
    thumbnail: require('../assets/Provence/barbegal_muehlen_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Barbegal: Wassermühlen',
    "lat": 43.702966,
    "lng": 4.721282,
    "description": "Barbegal: Wassermühlen",
    "Beschreibung": `An einem Abhang nordöstlich von Arles befindet sich die größte je gefundene römische Wassermühlenanlage. Der Komplex von Barbegal wurde im 2. Jhd. n. Chr. erbaut. Die Aquädukte, die das Wasser zuführten, sind noch gut erhalten. Wahrscheinlich befanden sich hier zwei Reihen von acht hintereinanderstehenden Wasserrädern. Die Anlage diente vermutlich dem Mahlen von Getreide, worauf auch nahegelegene Dreschplätze hindeuten.`,
    "Erreichbarkeit": "Route de l'Acqueduc, 13990 Fontvieille",
    "Literatur": "Robert H. J. Sellin: The large roman water mill at Barbegal. In: History of Technology, 8, 1983, Seite 91–109.",
  }, {
    src: require('../assets/Provence/arles_cryptoporticus.png'),
    thumbnail: require('../assets/Provence/arles_cryptoporticus_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Arles: Cryptoporticus',
    "lat": 43.676873,
    "lng": 4.627400,
    "description": "Arles: Cryptoporticus",
    "Beschreibung": `Der Kryptoportikus bildete einst den Unterbau des römischen Forums von Arles, da das Gelände in diesem Bereich abschüssig war. Der gewaltige Gewölbebau repräsentiert bis heute die enormen Möglichkeiten der römischen Bautechnik. Der gesamte Forumskomplex entstand in den frühen Regierungsjahren des Augustus. Doch vom einstigen Forum sind nur wenige Reste erhalten, und auch die einst offene Nordseite des Kryptoportikus liegt heute unterhalb des Bodenniveaus. Ob und wie die unterirdischen Räume genutzt wurden, ist umstritten. Vermutlich dienten sie als Lagerraum.`,
    "Erreichbarkeit": "5 Rue Balze, 13200 Arles",
    "Literatur": "Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/arles_thermen.png'),
    thumbnail: require('../assets/Provence/arles_thermen_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Arles: Konstantinsthermen',
    "lat": 43.678983,
    "lng": 4.626967,
    "description": "Arles: Konstantinsthermen",
    "Beschreibung": `Die Konstantinsthermen in Arles wurden im 4. Jhd. errichtet. Die öffentlichen Bäder dienten sowohl zur Körperhygiene als auch als sozialer Treffpunkt. In dieser typischen römischen Thermenanlage sind die zentralen Bereiche (caldarium, frigidarium, tepidarium, apodytherium) noch gut zu erkennen. In mehreren Räumen finden sich noch Teile der Fußbodenheizung (hypocaustum). Auch Teile der Mauern- und Gewölbe sind noch gut erhalten. Das Bauwerk entstand vorwiegend aus opus mixtum und spiegelt so die Mauertechnik der späten römischen Kaiserzeit wider.`,
    "Erreichbarkeit": "",
    "Literatur": "Erika Brödner: Die römischen Thermen und das antike Badewesen: eine kulturhistorische Betrachtung. Darmstadt 1992. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/arles_amphi.png'),
    thumbnail: require('../assets/Provence/arles_amphi_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Arles: Amphitheater',
    "lat": 43.677743,
    "lng": 4.630931,
    "description": "Arles: Amphitheater",
    "Beschreibung": `Das Amphitheater in Arles zählt zu den besterhaltenen Arenen des Altertums. Es wurde zum Ende des 1. Jhd. erbaut und zeigt die typischen Merkmale der römischen Bautechnik dieser Zeit. Wände, Bögen und Gewölbe bestehen aus mörtellosem Quadermauerwerk oder opus incertum, sogenannter „römischer Beton“ mit Schalung aus behauenen Natursteinen.`,
    "Erreichbarkeit": "1 Rond-Point des Arènes, 13200 Arles",
    "Literatur": "Heinz-Otto Lamprecht: Opus caementicium: Bautechnik der Römer, Düsseldorf 1996. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/orange_theater.png'),
    thumbnail: require('../assets/Provence/orange_theater_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Orange: Theater',
    "lat": 44.135864,
    "lng": 4.808851,
    "description": "Orange: Theater",
    "Beschreibung": `Das Theater in Orange zählt zu den besterhaltenen römischen Theaterbauten. Es wurde im 1. Jhd. erbaut und fasste etwa 10.000 Besucher, die sich auf mehrere Ränge verteilten. Das Bühnenhaus ist weitgehend erhalten, der Zuschauerraum teilweise rekonstruiert. Die römische Bautechnik mit Gewölben und sogenanntem „römische Beton“ (opus caementicium) ist gut erkennbar. Besonders interessant ist die Mischung aus der älteren griechischen Bauweise, die natürliche Hänge zur Anlage von Theatern nutzt, und der römischen Bauweise, die Theater freistehend aufrichtet.`,
    "Erreichbarkeit": "Rue Madeleine Roch, 84100 Orange",
    "Literatur": "Augustin-Nicolas Caristie: Monuments antiques à Orange: Arc de Triomphe et Théâtre. Paris 1856. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/orange_bogen.png'),
    thumbnail: require('../assets/Provence/orange_bogen_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Orange: Ehrenbogen',
    "lat": 44.142167,
    "lng": 4.804773,
    "description": "Orange: Ehrenbogen",
    "Beschreibung": `Der Ehrenborgen von Orange wurde vermutlich im frühen 1. Jhd. errichtet. Besonders interessant sind die Reliefs mit kriegerischen und nautischen Szenen. Dargestellt sind verschiedene Waffen, Rüstungen und Teile von Kriegsschiffen. Vermutlich handelt es sich unter anderem um Szenen der Kämpfe von Actium, die Augustus und Agrippa den Sieg über Antonius und Kleopatra brachten. Von verkehrshistorischem Interesse ist die den Ehrenbogen in Nord-Süd-Richtung durchlaufende Straße. Sie war einst der cardo maximus von Orange. Dieser war wiederum Teil der Via Agrippa, die unter anderem die römische Städte Arles und Lyon miteinander verband.`,
    "Erreichbarkeit": "Avenue de l'Arc de Triomphe, 84100 Orange",
    "Literatur": "Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/nimes_tempel.png'),
    thumbnail: require('../assets/Provence/nimes_tempel_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Nîmes: Tempel/Bibliothek',
    "lat": 43.839912,
    "lng": 4.348667,
    "description": "Nîmes: Tempel/Bibliothek",
    "Beschreibung": `In den Jardins de la Fontaine von Nîmes steht ein römisches Gebäude, dessen Funktion heute unbekannt ist. Es könnte sich um die Überreste eines Tempels oder einer Bibliothek handeln. Das Gebäude wurde im 2. Jhd. errichtet und ist bautechnisch durchaus interessant: Das Hauptschiff überspannt ein besonders massives Tonnengewölbe aus Quadermauerwerk, dessen Seitenschub durch die Gewölbe zweier Seitenschiffe aufgefangen wird.`,
    "Erreichbarkeit": "Quai Georges Clemenceau, 30000 Nîmes",
    "Literatur": "Hans Koepf: Baukunst in fünf Jahrtausenden. Stuttgart 1990. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/nimes_verteiler.png'),
    thumbnail: require('../assets/Provence/nimes_verteiler_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Nîmes: Wasserverteiler',
    "lat": 43.842367,
    "lng": 4.355982,
    "description": "Nîmes: Wasserverteiler",
    "Beschreibung": `Das castellum divisorium von Nîmes ist einer der am besten erhaltenen römischen Wasserverteiler. Die Anlage wurde im 1. Jhd. v. Chr. zusammen mit dem wasserzuführenden Aquädukt errichtet, das Quellwasser aus dem über 50 km entfernten Uzès heranführte. Der Wasserverteiler war ursprünglich überdacht. Gut zu erkennen sind die verschiedenen Abflüsse, von denen aus Bleirohre das Wasser zu den privaten und öffentlichen Gebäuden sowie zu den städtischen Laufbrunnen leiteten.`,
    "Erreichbarkeit": "14, 16 Rue de la Lampeze, 30000 Nîmes",
    "Literatur": "Frontinus-Gesellschaft e.V. (Hrsg.): Geschichte der Wasserversorgung, Band 2, Die Wasserversorgung antiker Städte, Mainz 1991.",
  }, {
    src: require('../assets/Provence/nimes_tour.png'),
    thumbnail: require('../assets/Provence/nimes_tour_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Nîmes: Tour Magne',
    "lat": 43.843069,
    "lng": 4.349359,
    "description": "Nîmes: Tour Magne",
    "Beschreibung": `Der noch gut erhaltene Tour Magne wurde im 1. Jhd. v. Chr. errichtet und bot mit seiner Höhe von 33 m einen guten Überblick über die Stadt und ihre Umgebung. Er war einst Teil der römischen Stadtbefestigung von Nîmes. Der keltische Ursprung des Bauwerks ist vor allem im Innenbereich noch gut erkennbar und weist eine relativ einfache Bauweise auf. Das Mauerwerk des Turms besteht aus sogenanntem „römischen Beton“ (opus caementicium) mit Schalung aus behauenem Naturstein. An den Außenbereichen, auf halber Höhe, sind die Wehrgänge der Stadtmauer zu erkennen.`,
    "Erreichbarkeit": "Les Jardins de la Fontaine, Place Guillaume Apollinaire, 30000 Nîmes",
    "Literatur": "Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/oppidum.png'),
    thumbnail: require('../assets/Provence/oppidum_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Nages-et-Solorgues: Keltisches Oppidum',
    "lat": 43.795230,
    "lng": 4.227017,
    "description": "Nages-et-Solorgues: Keltisches Oppidum",
    "Beschreibung": `Das Oppidum von Nages liegt in einem größeren keltischen Siedlungsbereich. Es wurde im 1. Jahrtausend v. Chr. errichtet und über einen Zeitraum von mehreren Jahrhunderten mehrmals umgebaut. Von besonderem technikhistorischem Interesse sind die teilweise rekonstruierte Stadtmauer mit Wehrtürmen und die Grundmauern verschiedener Gebäude. Bautechnisch interessant ist die ausschließliche Verwendung von mörtellosem Trockensteinmauerwerk.`,
    "Erreichbarkeit": "167 Chemin de Langlade, 30114 Nages-et-Solorgues",
    "Literatur": "Michel Py: L’oppidum des castels à Nages (Gard), Paris 1978.",
  }, {
    src: require('../assets/Provence/ambrussum_via.png'),
    thumbnail: require('../assets/Provence/ambrussum_via_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Ambrussum: Straße',
    "lat": 43.716160,
    "lng": 4.151279,
    "description": "Ambrussum: Straße",
    "Beschreibung": `Die befestigte Straße ist heute Teil eines archäologischen Parks. Sie liegt am östlichen Ausgang des antiken Ambrussum und wurde im 1. Jhd. gebaut. Einst verband sie den Ortskern mit der Via Domitia und der Pont Ambroix. Die Straße weißt eine Steigung von 9% auf. Die Spurrillen von und für Transportwagen sind gut erkennbar.`,
    "Erreichbarkeit": "Chemin d'Ambrussum, 34400 Villetelle",
    "Literatur": "http://www.ambrussum.com/494-the-museum.htm. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/ambrussum_pontamroix.png'),
    thumbnail: require('../assets/Provence/ambrussum_pontamroix_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Ambrussum: Pont Ambroix',
    "lat": 41.75475087,
    "lng": 12.28858519,
    "description": "Ambrussum: Pont Ambroix",
    "Beschreibung": `Die Brücke wurde in der Regierungszeit des Augustus erbaut. Sie war ursprünglich etwa 180 m lang und führte die Via Domitia über den Fluss Vidourle. Von den ehemals neun bis elf Bögen ist heute nur noch einer erhalten, da ein Hochwasser im Jahr 1840 den Großteil der Konstruktion zerstörte. Bis ins Spätmittelalter diente die Brücke noch dem Verkehr.`,
    "Erreichbarkeit": "Chemin d'Ambrussum, 34400 Villetelle",
    "Literatur": "Marcel Prade: Les ponts, monuments historiques: inventaire, description, histoire des ponts et ponts-aqueducs de France, protégés au titre des monuments historiques, Poitiers 1986. Raymond Chevallier: Römische Provence: Die Provinz Gallia Narbonensis, Luzern 1985.",
  }, {
    src: require('../assets/Provence/ambrussum_strassenstation.png'),
    thumbnail: require('../assets/Provence/ambrussum_strassenstation_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Ambrussum: Straßenstation',
    "lat": 43.719000,
    "lng": 4.149124,
    "description": "Ambrussum: Straßenstation",
    "Beschreibung": `Die römische Straßenstation in der Nähe des alten Ambrussum diente Reisenden auf der Via Domitia als Zwischenstopp. Der Gebäudekomplex entstand um 30 v. Chr. und ist heute Teil des archäologischen Parks von Ambrussum. Römische Straßenstationen umfassten in der Regel ein Gasthaus, Bäder, eine Schmiede, ein Postgebäude und Ställe Die Überreste dieser Straßenstation befinden sich leider in einem schlechten Zustand und sind nicht direkt zugänglich.`,
    "Erreichbarkeit": "Chemin d'Ambrussum, 34400 Villetelle",
    "Literatur": "http://www.ambrussum.com/494-the-museum.htm.",
  }, {
    src: require('../assets/Provence/pontdugard.png'),
    thumbnail: require('../assets/Provence/pontdugard_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Pont du Gard',
    "lat": 43.719000,
    "lng": 4.149124,
    "description": "Pont du Gard",
    "Beschreibung": `Der Pont du Gard ist einer der größten und besterhaltenen römischen Aquädukte. Er wurde im 1. Jhd. v. Chr. errichtet und war Teil jener Wasserleitung, die Nîmes mit frischem Wasser aus den etwa 50 km entfernten Quellen von Uzès versorgte. Das Bauwerk ist 275 m lang und 49 m hoch. Die Bogenkonstruktion überspannt den Fluss Gardon und diente bis in das 18. Jhd. auch als Straßenbrücke. Sehr empfehlenswert ist der Besuch des nahegelegenen Museums, das sich der Geschichte der römischen Wasserversorgung widmet.`,
    "Erreichbarkeit": "400 Route du Pont du Gard, 30210 Vers-Pont-du-Gard",
    "Literatur": "Frontinus-Gesellschaft e.V. (Hrsg.): Geschichte der Wasserversorgung, Band 2, Die Wasserversorgung antiker Städte, Mainz 1991.",
  }, {
    src: require('../assets/Provence/sernhac_tunnel.png'),
    thumbnail: require('../assets/Provence/sernhac_tunnel_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Sernhac: Tunnel/Aquädukt',
    "lat": 43.917009,
    "lng": 4.551546,
    "description": "Sernhac: Tunnel/Aquädukt",
    "Beschreibung": `Die Tunnel von Sernhac waren Teil der Wasserleitung von Uzès nach Nîmes. Das durch die Berge südlich des Pont du Gard führende System wurde im 1. Jhd. v. Chr. errichtet. An den Tunnelwänden sind die Spuren der römischen Meißel noch gut erkennbar. Längere Tunnelabschnitte und einige Wartungsschächte lassen sich noch immer begehen. In nachrömischer Zeit diente das Gebiet als Steinbruch. Daher wurden einige Tunnelabschnitte zerstört.`,
    "Erreichbarkeit": "440 Chemin de l'Aqueduc, 30210 Sernhac",
    "Literatur": "Frontinus-Gesellschaft e.V. (Hrsg.): Geschichte der Wasserversorgung, Band 2, Die Wasserversorgung antiker Städte, Mainz 1991.",
  }, {
    src: require('../assets/Provence/nimes_roemermuseum.png'),
    thumbnail: require('../assets/Provence/nimes_roemermuseum_tn.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Nîmes: Römermuseum',
    "lat": 43.833858,
    "lng": 4.359653,
    "description": "Nîmes: Römermuseum",
    "Beschreibung": `Das Musée de la Romanité von Nîmes präsentiert eine interessante Dauerausstellung zur Geschichte der Provence von den keltischen Ursprüngen bis zum Ende der römischen Provinz Gallia Narbonensis. Von besonderem technikhistorischem Interesse sind vor allem die Darstellungen und Artefakte handwerklicher und anderer beruflicher Tätigkeiten aus der Römerzeit. Die Abbildung, ein Grabrelief, zeigt einen pflügenden Bauern.`,
    "Erreichbarkeit": "16 Boulevard des Arènes, 30900 Nîmes",
    "Literatur": "https://museedelaromanite.fr/en/.",
  }
]
