export default [
 {
    src: require('../assets/Sizilien/Tempel_segesta.JPG'),
    thumbnail: require('../assets/Sizilien/Tempel_segesta.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: "Tempel in Segesta",
    "lat": 37.941287,
    "lng": 12.831998,
    "description": "Tempel in Segesta",
    "Beschreibung": "Der Tempel in dorischem Baustil steht in einer überblickenden Position auf einem Hügel. Dadurch dass der Tempel nie komplett fertiggestellt wurde tragen die Säulen noch eine Schutzschicht, welche durch Abtragung die Kanneluren formen sollte. Ebenso lassen sich Hinweise auf verwendete Bautechnik finden. So haben beispielsweise die verwendeten Steinblöcke noch die Hebebossen, die zum Einhängen der Seile verwendet wurden. Der Tempel ist auch ein schönes Beispiel für die Verwendung der Kurvatur in der Architektur. Hierbei werden gerade Gebäudekanten absichtlich leicht gewölbt, wodurch das Objekt harmischer aussieht. Auch die Entasis (Schwellung) der Säulen soll diesen Effekt erzielen.",
    "Erreichbarkeit": "Parco Archeologico di Segesta. Contrada Barbaro, 91013 Calatafimi TP. Öffnungszeiten: 9:00 - 16:30",
    "Literatur": "Brigit Carnabuci: Sizilien. Griechische Tempel, römische Villen, normannische Dome und barocke Städte im Zentrum des Mittelmeeres (= DuMont Kunst-Reiseführer). 6., aktualisierte Auflage. DuMont Reiseverlag, Ostfildern 2011, ISBN 978-3-7701-4385-6.         Eva Gründel, Heinz Tomek: Sizilien. DuMont Buchverlag, Köln, 5. Auflage 2001, ISBN 3-7701-3476-1      Dieter Mertens: „Der Tempel von Segesta“ und die Dorische Tempelbaukunst des Griechischen Westens in klassischer Zeit. Verlag Philipp von Zabern, Darmstadt 1984, ISBN 3-8053-0515-X.",
  }, {
    src: require('../assets/Sizilien/Kreuzgang.JPG'),
    thumbnail: require('../assets/Sizilien/Kreuzgang.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: "Kreuzgang des Klosters Monreale",
    "lat": 38.081662,
    "lng": 13.292429,
    "description": "Kreuzgang mit Blick auf Wehrturm",
    "Beschreibung": "Als typisches Element mittelalterlicher Klöster ist der Kreuzgang des Kloster eines der schönsten, noch erhaltenen Beispiele. Die Kapitelle der insgesamt 228 Säulen im arabischen Stil zeigen narrative Darstellungen. Beim Bau konnten die aufwendig hergestellten Säulen und Kapitelle wahrscheinlich nicht termingerecht fertiggestellt werden, die Bögen wurden aber schon auf einem Gerüst gebaut. Davon zeugen die Wulste im inneren der Bögen, mit Öffnungen zum Einsatz von Zapfen. Die fertigen Säulen konnten dann im nachhinein eingefügt werden. Die einzelnen Säulen stehen jeweils auf Bleiplatten. Die Duktilität des Bleis sorgt für eine Art gedäpfte Lagerung der Säulen, wodurch, trotz Erdbeben, alle Säulen noch heute intakt sind.",
    "Erreichbarkeit": "Cattedrale di Monreale, Monreale. In 30 Minuten leicht von Palermo über die SS186 zu erreichen.",
    "Literatur": "Brigit Carnabuci: Sizilien. Griechische Tempel, römische Villen, normannische Dome und barocke Städte im Zentrum des Mittelmeeres (= DuMont Kunst-Reiseführer). 6., aktualisierte Auflage. DuMont Reiseverlag, Ostfildern 2011, ISBN 978-3-7701-4385-6.",
  }, {
    src: require('../assets/Sizilien/Brunnen.JPG'),
    thumbnail: require('../assets/Sizilien/Brunnen.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: "Brunnen",
    "lat": 38.081368,
    "lng": 13.292130,
    "description": "Brunnenhof",
    "Beschreibung": "In der Südwestecke des Kreuzganges befindet sich zusätzlich der aus 3 x 3 Arkaden bestehende Brunnenhof. Als typisches Element der arabischen Architektur zeugt dieser von der Synthese aus arabisch-byzantinisch-normannischer Architektur, die es so nur auf Sizilien gibt.",
    "Erreichbarkeit": "Cattedrale di Monreale, Monreale. In 30 Minuten leicht von Palermo über die SS186 zu erreichen.",
    "Literatur": "Brigit Carnabuci: Sizilien. Griechische Tempel, römische Villen, normannische Dome und barocke Städte im Zentrum des Mittelmeeres (= DuMont Kunst-Reiseführer). 6., aktualisierte Auflage. DuMont Reiseverlag, Ostfildern 2011, ISBN 978-3-7701-4385-6.",
  }, {
    src: require('../assets/Sizilien/Bronzeportal.jpg'),
    thumbnail: require('../assets/Sizilien/Bronzeportal.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: "Bronzeportal",
    lat: 38.081916,
    "lng": 13.291835,
    "description": "Bronzeportal",
    "Beschreibung": "Unter dem im 18. Jahrhundert vorgebauten, klassizistischen Portikus befindet sich das Bronzeportal, vermutlich von Bonannus von Pisa 1186 hergestellt, und zeigt 42 Darstellungen mit biblischen Motiven. Das Spitzbogen-Portal im arabischen-normannischen Stil hat keinen Waagrechten Sturz, der typischen romanischen Kirchen",
    "Erreichbarkeit": "Cattedrale di Monreale, Monreale. In 30 Minuten leicht von Palermo über die SS186 zu erreichen.",
    "Literatur": "Brigit Carnabuci: Sizilien. Griechische Tempel, römische Villen, normannische Dome und barocke Städte im Zentrum des Mittelmeeres (= DuMont Kunst-Reiseführer). 6., aktualisierte Auflage. DuMont Reiseverlag, Ostfildern 2011, ISBN 978-3-7701-4385-6.",
  }, {
    src: require('../assets/nemisee_thumbnail.png'),
    "lat": 41.71224887,
    "lng": 12.69442116,
    "description": "Nemisee Entwässerungskanal",
    "Beschreibung": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "Erreichbarkeit": "Wo, Wann offen",
    "Literatur": "Literatur",
  },{
    src: require('../assets/Sizilien/Kapitell.JPG'),
    thumbnail: require('../assets/Sizilien/Kapitell.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: "Widmungskapitell: Wilhelm II. widmet Kloster und Kirche der heiligen Maria",
    "lat": 38.081450,
    "lng": 13.292067,
    "description": "Widmungskapitell",
    "Beschreibung": "Die Kathedrale Santa Maria Nuova in Monreale ist, wie der Name vermuten lässt, der heiligen Maria gewidmet. Das Widmungskapitell an einer der viele Säulen des Kreuzganges zeigt Wilhelm den II. wie er Kloster und Kirche der heiligen Maria widmet; ein Engel hilft, den Dom zu tragen. Beachtlich ist die Handwerkskunst mit der die Kapitelle gefertigt wurden. Zusätzlich zum altbekannten Arkanthusblatt werden hier die Kapittelle als architektonisches Element neu entdeckt und erzählen Geschichten aus der Bibel, dem Alltag oder der Mythologie. Alle 104 Doppelkapitelle und die 5 Viererkapitelle des Kreuzganges findet man in digitalisierter Form auf http://cenobium.isti.cnr.it/monreale/capitals    ",
    "Erreichbarkeit": "Cattedrale di Monreale, Monreale. In 30 Minuten leicht von Palermo über die SS186 zu erreichen.",
    "Literatur": "BrigitCarnabuci: Sizilien. Griechische Tempel, römische Villen, normannische Dome und barocke Städte im Zentrum des Mittelmeeres (= DuMont Kunst-Reiseführer). 6., aktualisierte Auflage. DuMont Reiseverlag, Ostfildern 2011, ISBN 978-3-7701-4385-6.",
  }, {
    src: require('../assets/pics/Latium/nemisee_thumbnail.png'),
    "lat": 41.71224887,
    "lng": 12.69442116,
    "description": "Nemiseeentwässerungskanal",
    "Beschreibung": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "Erreichbarkeit": "Wo, Wann offen",
    "Literatur": "Literatur: Vitruv: Über die Baukunst. De architectura, Erich Stürzenacker (Hg.), Essen, 1938.; Alfred Heuß/Jochen Bleicken: Römische Geschichte, Paderborn u.a., 2003.",
  }, {
    src: require('../assets/pics/Latium/SAM_6272.JPG'),
    "lat": 41.85091321,
    "lng": 12.55399734,
    "description": "Park der Aquädukte",
    "Beschreibung": "Parco degli Acquedotti / Parco dei 7 Acquedotti, u.a. folgende Teilabschnitte der Aquädukte: Arkaden der Aquädukte Aqua Claudia, Anio Novus und Acqua Felice; / Teil des Regionalparks Via Appia Antica",
    "Erreichbarkeit": "Weblink: http://www.parcoacquedotti.it",
    "Literatur": "Literatur",
  }, {
    src: require('../assets/pics/Latium/SAM_6272.JPG'),
    "lat": 41.75497325,
    "lng": 12.28943535,
    "description": "Mühlen der Bäckerei",
    "Beschreibung": "Bäckerei in Ostia Antica mit eigenen, noch gut erhaltenen Mühlen. Die Mühlen bestehen aus einem kegelförmigen Unterbau mit einem zylinderförmigen Aufsatz zwischen denen Getreide gemahlen wurde. Zum drehen des Zylinders wurde ein Holzbalken verwendet, der durch Maulesel oder Menschen betrieben wurde.",
    "Erreichbarkeit": "Öffnungszeit je nach Jahreszeit: 9:00 bis 15:30 im Winter und 18:15 im Sommer Weblink: http://www.ostiaantica.beniculturali.it",
    "Literatur": "Literatur",
  }, {
    src: require('../assets/pics/Latium/SAM_6272.JPG'),
    "lat": 41.75672445,
    "lng": 12.29201520,
    "description": "Unterbau der Neptun Therme",
    "Beschreibung": "Die Neptun Therme ist besonders für ihre schwarz-weiß Mosaike bekannt. Die Unterkonstruktion aus einem Hipokaustum ist bei der Neptun Therme besonders gut zu erkennen. Auch die Öfen zur Beheizung sind teilweise noch vorhanden",
    "Erreichbarkeit": "Archäoligischer Park Ostia Antica; Öffnungszeit je nach Jahreszeit: 9:00 bis 15:30 im Winter und 18:15 im Sommer; Link: ostiaantica.beniculturali.it",
    "Literatur": "",
  }, {
    src: require('../assets/pics/Latium/SAM_6272.JPG'),
    "lat": 41.75665568,
    "lng": 12.29174278,
    "description": "Brunnen der Neptun Therme",
    "Beschreibung": "",
    "Erreichbarkeit": "Archäoligischer Park Ostia Antica; Öffnungszeit je nach Jahreszeit: 9:00 bis 15:30 im Winter und 18:15 im Sommer; Link: ostiaantica.beniculturali.it",
    "Literatur": "",
  }, {
    src: require('../assets/pics/Latium/SAM_6272.JPG'),
    thumbnail: require('../assets/pics/Latium/SAM_6272.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Latrine der Neptun Therme',
    "lat": 41.75672445,
    "lng": 12.29241524,
    "description": "Latrine der Neptun Therme",
    "Beschreibung": "Die Neptun therme verfügt über seine eigene öffentliche Latrine in der nord-westlichen Ecke der Anlage. Die Sitzbank aus Stein ist sehr gut erhalten, Die Latrine galt als Ort für Gespräche und Geschäfte.",
    "Erreichbarkeit": "Archäoligischer Park Ostia Antica; Öffnungszeit je nach Jahreszeit: 9:00 bis 15:30 im Winter und 18:15 im Sommer; Link: ostiaantica.beniculturali.it",
    "Literatur": "",
  }, {
    src: require('../assets/Sizilien/peristyl.JPG'),
    thumbnail: require('../assets/Sizilien/peristyl.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Peristylhof',
    "lat": 37.430428,
    "lng": 14.481137,
    "description": "Peristylhof",
    "Beschreibung": "Das typisch griechische Peristyl (peri „um herum“ und stylos „Säule“) ist der hier zu sehende, von Säulen umgebene, Innenhof. Dieses architektonische Element wurde auch bei den Römern beliebt. So empfahl Vitruv  für die Villa die Abfolge von Eingang, Peristyl und Atrium in der Mittelachse des Gebäudes, während für das Stadthaus die umgekehrte Abfolge üblich war, bei der im Eingangsbereich das Atrium liegt und das Peristyl im hinteren, privateren Bereich des Hauses.",
    "Erreichbarkeit": "Sito archeologico di Morgantina, erreichbar über die SS288, nahe Piazza Armerina",
    "Literatur": "Wilfried Koch: Baustilkunde, Bertelsmann Lexikon Institut, 2003, ISBN 3-577-10457-0",
  }, {
    src: require('../assets/Sizilien/wasserleitung_detail.JPG'),
    thumbnail: require('../assets/Sizilien/wasserleitung_detail.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Wasserleitung',
    "lat": 38.094158,
    "lng": 13.532066,
    "description": "Waserleitung - Opus Signinum",
    "Beschreibung": "Ausschnitt einer überdachten Wasserleitung. Es lassen sich die verschieden Schichten des Aufbaus erkennen. Bei der rosa-farbigen Schicht handelt sich um Opus Signinum. Dieser wird aus einem Gemisch aus fein zerschlagenen Tonscherben, Sandsorten, Kalkmörtel, Ziegelmehl sowie Kies, Terracotta- oder Keramikfragmenten und -soweit regional verfügbar- natürlichen Puzzolanen gefertigt. Der erhärtete Estrich wurden mit einer Schicht aus Leinöl überzogen und solange poliert, bis die Oberfläche glatt wie Marmor wurde. Im Falle einer Wasserleitung ging es hierbei nicht um den optischen Eindruck sondern vielmehr darum eine möglichst glatte und wasserdichte Oberfläche zu schaffen, welche Kalkablagerungen verhindert.",
    "Erreichbarkeit": "Area Archeologica di Solunto. Solunto is kurz vor Palermo leicht von der SS113 zu erreichen.",
    "Literatur": " Plinius der Ältere: Naturalis historia. Buch 35, Kapitel 46.  Vitruv: De Architectura. Buch VII, F. Sear: Roman Wall and Vault Mosaics. Heidelberg 1977.",
  }, {
    src: require('../assets/Latium/roemischesvorratslager.jpg'),
    thumbnail: require('../assets/Latium/roemischesvorratslager.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Römische Vorratslager',
    "lat": 41.75506983,
    "lng": 12.28805077,
    "description": "Römische Vorratslager",
    "Beschreibung": "Das römische Vorratslager bestand aus in den Boden eingelassenen Amphoren (dolien), die zumeist mit Öl und Wein gefüllt wurden. Markant ist die Größe der einzelnen Amphoren, welches auf eine dauerhafte Nutzung als stationäre Vorratsgefäße schließen lässt. Die Einlassung der Behälter in den Boden verfolgte den Zweck der Kühlung. Abschließend wurden die Amphoren mit zumeist Lederabdeckungen verschlossen um die Güter vor Witterungseinflüssen und Ungeziefer zu schützen.",
    "Erreichbarkeit": "Archäoligischer Park Ostia Antica; Öffnungszeit je nach Jahreszeit: 9:00 bis 15:30 im Winter und 18:15 im Sommer; Link: ostiaantica.beniculturali.it",
    "Literatur": "Alfred Heuß/Jochen Bleicken: Römische Geschichte, Paderborn u.a., 92003.,Dieter Hägermann/Helmuth Schneider: Landbau und Handwerk : 750 v. Chr. bis 1000 n. Chr.. Propyläen-Technikgeschichte Bd 1, Berlin, 2003. Helmuth Schneider: Geschichte der antiken Technik, München, 22012.",
  }, {
    src: require('../assets/Sizilien/latrine.JPG'),
    thumbnail: require('../assets/Sizilien/latrine.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Latrine',
    "lat": 37.364638,
    "lng": 14.335021,
    "description": "Latrine mit Bodenmosaik",
    "Beschreibung": "Der hier gezeigte Ausschnitt zeigt die Sitzmöglichkeiten einer römischen Latrinen. Man saß nebeneinander und teilweise sich gegenüber während man sich erleichterte. Gut zu sehen ist der Abwasserkanal, der unter den Toilettensitzen verläuft. Durch eine konstante Wasserversorgung wurde Fäkalien weggespült. Nicht selten wurden diese Abwässer in nahe gelegene Felder geleitet und als Dünger verwertet.",
    "Erreichbarkeit": "Villa Romana del Casale, in circa 3 km Entfernung von Piazza Armerina",
    "Literatur": "",
  }, {
    src: require('../assets/Sizilien/hypokaustenheizung2.JPG'),
    thumbnail: require('../assets/Sizilien/hypokaustenheizung2.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Hypokaustum - Unterbau',
    "lat": 37.364871,
    "lng": 14.334114,
    "description": "Hypokaustenheizung, Unterbau",
    "Beschreibung": "Der zu heizende Raum bestand aus im Abstand von etwa 30 bis 40 cm aufgeschichteten, etwa 30 bis 60 cm hohen Ziegeltürmchen aus quadratischen Platten. Auf diesen Türmchen wurden größere Deckplatten aufgebracht auf welchen wiederum eine große Tragplatte mit Estrich lag. Diese relative dicke Konstruktion benötigte mehrere Stunden, wenn nicht ein oder zwei Tage bis zur völligen Erwärmung. Die heiße Luft strömte an den Wandkanälen (tubuli) in Freie. Auf diese Weise konnten auch die Wände des Raums beheizt werden.",
    "Erreichbarkeit": "Villa Romana del Casale, in circa 3 km Entfernung von Piazza Armerina",
    "Literatur": "Gustav Fusch: Über Hypokausten-Heizungen und mittelalterliche Heizungsanlagen. Dissertation Hannover 1910. Heinz-Otto Lamprecht: Heizung. In: Der Neue Pauly (DNP). Band 5, Metzler, Stuttgart 1998, ISBN 3-476-01475-4, Sp. 258–261. Hannes Lehar: Die römische Hypokaustheizung. Berechnungen und Überlegungen zu Leistung, Aufbau und Funktion. Shaker, Aachen 2012",
  }, {
    src: require('../assets/Sizilien/ziegelmauer.JPG'),
    thumbnail: require('../assets/Sizilien/ziegelmauer.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Lehmziegelmauer',
    "lat": 37.071284,
    "lng": 14.223443,
    "description": "Lehmziegelmauer",
    "Beschreibung": "Im Jahre 333 vor Christus wurde diese 8 Meter hohe Befestigungsmauer errichtet. Sie diente dazu, große Sandmengen, die von der Küste in Richtung der Stadt geweht wurden aufzuhalten. Die Befestigungsanlage ist noch sehr gut erhalten, da sie bis zu ihrer Entdeckung im 20ten Jahrhundert von Dünen bedeckt war.",
    "Erreichbarkeit": "Fortificazioni Greche di Capo Soprano (Mura Timoleontee), Gela",
    "Literatur": "https://www.lonelyplanet.com/italy/gela/attractions/greek-fortifications-of-capo-soprano/a/poi-sig/1024037/1003652                                            ----- http://www.sicilia-by-divino.com/gela.html",
  }, {
    src: require('../assets/Sizilien/Muehle.jpg'),
    thumbnail: require('../assets/Sizilien/Muehle.jpg'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Mühle',
    "lat": 37.4310005,
    "lng": 14.4785498,
    "description": "Mühle",
    "Beschreibung": "Das Getreide wurde in die trichterförmige Öffnung der Steinmühle gegeben und zwischen den Mahlsteinen zerrieben. Der obere Mahlstein konnte mittels einer Vorrichtung aus Holz durch menschliche oder tierische Arbeit in Bewegung gesetzt werden. Steinmühlen konnten große Mengen an Getreide in relativ kurzer Zeit mahlen.",
    "Erreichbarkeit": "Sito archeologico di Morgantina, erreichbar über die SS288, nahe Piazza Armerina",
    "Literatur": "http://www.amuseum.de/physik/alwaze/alwazehist.htm",
  }, {
    src: require('../assets/Sizilien/hypokaustenheizung1.JPG'),
    thumbnail: require('../assets/Sizilien/hypokaustenheizung1.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Hypokaustum - Ofen',
    "lat": 37.364977,
    "lng": 14.333966,
    "description": "Hypokaustenheizung, Ofen",
    "Beschreibung": "Der hier sichtbare Teil des Heizungssystems der Thermen der Villa Romana del Casale, einer spätrömischen Villa urbana, zeigt einen Brennofen. Hier wurde Holz verbrannt um mit der heißen Luft den, unter dem Fußboden liegenden, Heizraum zu erwärmen. Als typisches Merkmal der römischen Baukunst ist die Rundbogenkonstruktion zu erkennen. Tatsächlich war der gesammte Brennraum mit einem Tonnengewölbe überdacht. Hinweise auf dieses Gewölbe lassen sich an den Innenwänden erkennen. Hier befinden sich Reste der holen Tonzylinder, die durch das Zusammenstecken einen Bogen spannten.",
    "Erreichbarkeit": "Villa Romana del Casale, in circa 3 km Entfernung von Piazza Armerina",
    "Literatur": "Gustav Fusch: Über Hypokausten-Heizungen und mittelalterliche Heizungsanlagen. Dissertation Hannover 1910. Heinz-Otto Lamprecht: Heizung. In: Der Neue Pauly (DNP). Band 5, Metzler, Stuttgart 1998, ISBN 3-476-01475-4, Sp. 258–261. Hannes Lehar: Die römische Hypokaustheizung. Berechnungen und Überlegungen zu Leistung, Aufbau und Funktion. Shaker, Aachen 2012,",
  }, {
    src: require('../assets/Sizilien/ziegelofen.JPG'),
    thumbnail: require('../assets/Sizilien/ziegelofen.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Brennofen',
    "lat": 37.430647,
    "lng": 14.480064,
    "description": "Brennofen",
    "Beschreibung": "Dieser Ausschnitt ziegt die obere Öffnung eines Brennofens. Darunter wurden keramische Objekte gestapelt und gebrannt. Die Löcher dienten dienten als Abluftkanäle. Die Kapazität dieser Öfen verierte, in einigen Baurten konnten aber mehrere tausend Teile gebrannt werden. Gefeuert wurde in einer separaten Brennkammer von der aus die heiße Luft in den Ofen und anschließend in Freie strömte.",
    "Erreichbarkeit": "Sito archeologico di Morgantina, erreichbar über die SS288, nahe Piazza Armerina",
    "Literatur": "http://www.antike-tischkultur.de/keramikbrennofen.html",
  }, {
    src: require('../assets/Sizilien/theater.JPG'),
    thumbnail: require('../assets/Sizilien/theater.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Griechisches Theater',
    "lat": 37.430078,
    "lng": 14.479334,
    "description": "Griechisches Theater",
    "Beschreibung": "Das in einen flachen Hang integrierte Freilufttheater bestand aus kreisförmig angeordneten Stufen, welche die nicht mehr erhaltene Orchestra umgaben. Diese Sitzreihen wurden durch die im Bild erkennbaren horizontale Korridore (Diazoma) unterteilt. Resultat der typischen Bauweise der griechischen Theater war und ist die hervorragende Akustik.",
    "Erreichbarkeit": "Sito archeologico di Morgantina, erreichbar über die SS288, nahe Piazza Armerina",
    "Literatur": "http://griechischestheater.npage.de/bauweise.html",
  }, {
    src: require('../assets/Sizilien/griechischesbad.JPG'),
    thumbnail: require('../assets/Sizilien/griechischesbad.JPG'),
    thumbnailWidth: null,
    thumbnailHeight: null,
    caption: 'Griechisches Bad',
    "lat": 37.072637,
    "lng": 14.230494,
    "description": "Griechisches Bad",
    "Beschreibung": "Die griechischen Bäder von Gela datieren auf das vierte oder dritte Jahrhundert vor Christus. Sie setzten sich aus zwei verschiedenen Räumen zusammen, die wahrscheinlich von einem typischen Terrakotta Dach bedeckt waren. Im ersten Raum befanden sich mehrere Becken, kreisförmig angeordnet und durch Rohre miteinander verbunden. Es gab keinen Abfluss. Die Becken mussten von Hand geleert werden. Im zweiten Raum diente der untere Teil als Hypokaustum - vermutlich für eine darüberliegende Sauna. ",
    "Erreichbarkeit": "Innenstadt Gela, Via Europa",
    "Literatur": "Pietro Orlandini: Gela. Impianto greco di bagni pubblici presso l'ospizio, in Notizie degli scavi, 1960. Der Neue Pauly (DNP). Band 5, Metzler, Stuttgart 1998, ISBN 3-476-01475-4, Sp. 258–261.",
  }
]
